# Generated by Django 2.2.7 on 2019-11-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_custommodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommodels',
            name='upload',
            field=models.FileField(upload_to='datasets/% Y/% m/% d/'),
        ),
    ]
