# Generated by Django 2.2.7 on 2019-11-09 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20191109_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommodels',
            name='upload',
            field=models.FileField(upload_to='datasets/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'tsv'])]),
        ),
    ]
