# Generated by Django 2.2.7 on 2019-11-10 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20191110_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommodels',
            name='model',
            field=models.FileField(default='1', upload_to='datasets/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'tsv'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custommodels',
            name='pre_model',
            field=models.FileField(upload_to='datasets/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'tsv'])]),
        ),
    ]
