# Generated by Django 2.2.7 on 2019-11-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20191110_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custommodels',
            old_name='model',
            new_name='cus_model',
        ),
    ]
