# Generated by Django 2.2.7 on 2019-11-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20191110_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommodels',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
    ]
