# Generated by Django 2.2.7 on 2019-11-10 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_custommodels_pre_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommodels',
            name='temp_data',
            field=models.FileField(default='1', upload_to='datasets/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'tsv'])]),
            preserve_default=False,
        ),
    ]
