# Generated by Django 2.2.7 on 2019-11-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20191111_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommodels',
            name='model_used_name',
            field=models.CharField(default='Random Forest', max_length=255),
            preserve_default=False,
        ),
    ]
